services:
  db:
    image: mysql:8.2
    container_name: example-mysql-db
    env_file:
      - .env
    volumes:
      - example_mysql_db_data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306" # "localport:containerport"
    

volumes:
  example_mysql_db_data:
    external: true