services:
  db:
    image: mysql:8.2
    container_name: example-mysql-db-server
    env_file:
      - .env
    volumes:
      - example-mysql-db-data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306" # "localport:containerport"
    

volumes:
  example-mysql-db-data:
    external: true